package pojo;
// Generated Oct 11, 2023 3:00:53 PM by Hibernate Tools 4.3.1

import DAOAdmin.DAOLoginAdmin;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;




/**
 * Admin generated by hbm2java
 */
@ManagedBean
public class Admin  implements java.io.Serializable {


     private String username;
     private String password;

    public Admin() {
    }

    public Admin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

public void save()
    {
        DAOLoginAdmin pdao=new DAOLoginAdmin();
        pdao.addAdmin(this);
    }

    public void delete()
    {    
        DAOLoginAdmin pdao=new DAOLoginAdmin();
        pdao.deleteAdmin(username);
    }

    public List<Admin> getbyid()
    { 
        DAOLoginAdmin pdao=new DAOLoginAdmin();
        List<Admin> prod=pdao.getbyID(username);
        password=prod.get(0).password;
        return prod;
    }

    public List<Admin> getallrecords()
    {
        DAOLoginAdmin pdao=new DAOLoginAdmin();
        List<Admin> prod=pdao.retrieveAdmin();
        return prod;
    }

    public void update()
    {
        DAOLoginAdmin pdao=new DAOLoginAdmin();
        pdao.updateAdmin(this);
    }
    
    public String validateAdmin()
    { 
        try {
            DAOLoginAdmin pdao=new DAOLoginAdmin();
            List<Admin> prod=pdao.validateLogin(username, password);
            username=prod.get(0).username;
            password=prod.get(0).password;
            
            FacesContext context = FacesContext.getCurrentInstance();
            if(username != null) {
                context.getExternalContext().getSessionMap().put("username", username);
                return "index";
            }
            else {
                return "GagalLogin";
            }
        }
        catch(Exception ex) {
            return "GagalLogin";
        }
        //return prod;
    }
    
    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "adminLogin";
    }


}


