package pojo;
// Generated Oct 7, 2023 2:21:55 AM by Hibernate Tools 4.3.1


import DAOMembership.DAOClassMembership;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;

/**
 * Classmembership generated by hbm2java
 */
@ManagedBean
public class Classmembership  implements java.io.Serializable {


     private Integer idClassMembership;
     private Classes classes;
     private Member member;
     private Trainer trainer;
     private Date startDate;
     private Date endDate;
     private Set attendances = new HashSet(0);

    public Classmembership() {
    }

	
    public Classmembership(Classes classes, Member member, Trainer trainer, Date startDate, Date endDate) {
        this.classes = classes;
        this.member = member;
        this.trainer = trainer;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public Classmembership(Classes classes, Member member, Trainer trainer, Date startDate, Date endDate, Set attendances) {
       this.classes = classes;
       this.member = member;
       this.trainer = trainer;
       this.startDate = startDate;
       this.endDate = endDate;
       this.attendances = attendances;
    }
   
    public Integer getIdClassMembership() {
        return this.idClassMembership;
    }
    
    public void setIdClassMembership(Integer idClassMembership) {
        this.idClassMembership = idClassMembership;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Trainer getTrainer() {
        return this.trainer;
    }
    
    public void setTrainer(Trainer trainer) {
        this.trainer = trainer;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }

    public List<Classmembership> getAllRecord() {
        DAOClassMembership prd = new DAOClassMembership();
        List<Classmembership> Lprd = prd.retrieveClassmembership();
        return Lprd;
     }
     
     public void save_cms() {
        DAOClassMembership add = new DAOClassMembership();
        add.add_Cms(this);
    }

        public String getById() {
        String idClassmembership = null;
        idClassmembership = idClassmembership.toString();
        DAOClassMembership prd = new DAOClassMembership();
        List<Classmembership> lprd = prd.getbyID(idClassmembership);
        idClassMembership = lprd.get(0).idClassMembership;
        classes = lprd.get(0).classes;
        member = lprd.get(0).member;
        trainer = lprd.get(0).trainer;
        startDate = lprd.get(0).startDate;
        endDate = lprd.get(0).endDate;
        return "HalamanMembership";
    }
            public String edit() {
        DAOClassMembership train = new DAOClassMembership();
        train.editCms(this);
        classes = this.getClasses();
        member = this.getMember();
        trainer = this.getTrainer();
        startDate = this.getStartDate();
        endDate = this.getEndDate();
        FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO, "Berhasill Update Data", null);
        return "HalamanMembership";
    }

    public String delete() {
        DAOClassMembership train = new DAOClassMembership();
        train.deleteCms(idClassMembership);
        return "HalamanMembership";
    }



}


