package pojo;
// Generated Oct 6, 2023 10:26:26 PM by Hibernate Tools 4.3.1


import DAOMember.DAOAddMember;
import DAOMember.DAOLoginMember;
import DAOMember.DAOTampilMember;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Member generated by hbm2java
 */
@ManagedBean
public class Member  implements java.io.Serializable {


     private Integer idMember;
     private String memberName;
     private String email;
     private String password;
     private int phone;
     private String address;
     private Date dateBirth;
     private Set classmemberships = new HashSet(0);

    @Override
    public String toString() {
        return "Member{" + "idMember=" + idMember + ", memberName=" + memberName + ", email=" + email + ", password=" + password + ", phone=" + phone + ", address=" + address + ", dateBirth=" + dateBirth + '}';
    }

    public Member() {
    }

	
    public Member(String memberName, String email, String password, int phone, String address, Date dateBirth) {
        this.memberName = memberName;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.address = address;
        this.dateBirth = dateBirth;
    }
    public Member(String memberName, String email, String password, int phone, String address, Date dateBirth, Set classmemberships) {
       this.memberName = memberName;
       this.email = email;
       this.password = password;
       this.phone = phone;
       this.address = address;
       this.dateBirth = dateBirth;
       this.classmemberships = classmemberships;
    }
   
    public Integer getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(Integer idMember) {
        this.idMember = idMember;
    }
    public String getMemberName() {
        return this.memberName;
    }
    
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getDateBirth() {
        return this.dateBirth;
    }
    
    public void setDateBirth(Date dateBirth) {
        this.dateBirth = dateBirth;
    }
    public Set getClassmemberships() {
        return this.classmemberships;
    }
    
    public void setClassmemberships(Set classmemberships) {
        this.classmemberships = classmemberships;
    }

//Proses login member
          public String validasiUser() {
        DAOLoginMember uDao = new DAOLoginMember();
        List<Member> us = uDao.getBy(email, password);
          try 
        { if (us != null) {
            email = us.get(0).email;
            password = us.get(0).password;
            return "index";
        }
        
    } catch (Exception e) {
    }
        return "GagalLogin";
    }

public void savedata()
{
    DAOAddMember add = new DAOAddMember();
add.tambah(this);
}

public List<Member> tabelmember()
{
DAOTampilMember tdao=new DAOTampilMember();
    List<Member> kar = tdao.ambilmember();
    System.out.println(kar);
    return kar;
}

            public String edit() {
        DAOClassMembership train = new DAOClassMembership();
        train.editCms(this);
        classes = this.getClasses();
        member = this.getMember();
        trainer = this.getTrainer();
        startDate = this.getStartDate();
        endDate = this.getEndDate();
        FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO, "Berhasill Update Data", null);
        return "HalamanMembership";
    }
}


