package pojo;
// Generated Oct 7, 2023 2:21:55 AM by Hibernate Tools 4.3.1


import DAOMember.DAOAddMember;
import DAOMember.DAOLoginMember;
import DAOMember.DAOTampilMember;
import DAOTrainer.DAOLoginTrainer;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;
/**
 * Trainer generated by hbm2java
 */
@ManagedBean
public class Trainer  implements java.io.Serializable {


     private Integer idTrainer;
     private String trainerName;
     private String email;
     private String password;
     private int phoneNumber;
     private Set classmemberships = new HashSet(0);

    public Trainer() {
    }

	
    public Trainer(String trainerName, String email, String password, int phoneNumber) {
        this.trainerName = trainerName;
        this.email = email;
        this.password = password;
        this.phoneNumber = phoneNumber;
    }
    public Trainer(String trainerName, String email, String password, int phoneNumber, Set classmemberships) {
       this.trainerName = trainerName;
       this.email = email;
       this.password = password;
       this.phoneNumber = phoneNumber;
       this.classmemberships = classmemberships;
    }
   
    public Integer getIdTrainer() {
        return this.idTrainer;
    }
    
    public void setIdTrainer(Integer idTrainer) {
        this.idTrainer = idTrainer;
    }
    public String getTrainerName() {
        return this.trainerName;
    }
    
    public void setTrainerName(String trainerName) {
        this.trainerName = trainerName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Set getClassmemberships() {
        return this.classmemberships;
    }
    
    public void setClassmemberships(Set classmemberships) {
        this.classmemberships = classmemberships;
    }


public String validasiTrainer() {
    DAOLoginTrainer uDao = new DAOLoginTrainer();
    List<Trainer> us = uDao.getBy(email, password);
    try { 
        if (us != null) {
            email = us.get(0).email;
            password = us.get(0).password;
            return "index";
        }
    } catch (Exception e) {
        // Handle any exceptions here, if needed
    }
    return "GagalLogin";
}
}


